server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: mysql
  application:
    name: yilei-tryshop
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.102:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  scan:
    base-packages: com.yilei.tryshop.apiservice
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: yilei-tryshop
